info:
  contact: {}
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Healthz
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthz
      tags:
      - healthz
  /metrics:
    get:
      consumes:
      - application/json
      description: Metrics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Metrics
      tags:
      - metrics
swagger: "2.0"
